# Jekyll Resume Theme

# Site settings
title: Reesha Rajen
email: email@domain.com
description: Jekyll Resume is a mega simple resume theme for Jekyll.
baseurl: ""
url: "https://rajenr.github.io"
name: Reesha Rajen
job: student
location: La Jolla, CA
languages: Java, C++, Python, C#
twitter_username: mattcouchman
github_username:  rajenr
codepen_username:  mattcouchman
email_address: rrajen@ucsd.edu

# Build settings
markdown: kramdown
