# Jekyll Resume Theme

# Site settings
title: Reesha Rajen
email: email@domain.com
description: Jekyll Resume is a mega simple resume theme for Jekyll.
baseurl: ""
url: "https://rajenr.github.io"
name: Reesha Rajen
job: student
location: San Diego, CA
languages: Java, C++, and C#
twitter_username: mattcouchman
github_username:  rajenr
codepen_username:  mattcouchman
email_address: rajen.reese@gmail.com

# Build settings
markdown: kramdown
